# Generated by Django 6.0.1 on 2026-01-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neuro-Training Run', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Dataset'), ('downloading', 'Downloading from Kaggle'), ('preprocessing', 'Preprocessing Clinical Data'), ('training', 'Deep Learning Active'), ('completed', 'Training Successful'), ('failed', 'Training Failed')], default='pending', max_length=20)),
                ('dataset_source', models.CharField(default='Kaggle: amananandrai/complete-eeg-dataset', max_length=255)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_loss', models.FloatField(blank=True, null=True)),
                ('current_accuracy', models.FloatField(blank=True, null=True)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NeuralModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('accuracy', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('weights_file', models.FileField(blank=True, null=True, upload_to='models/weights/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
