# Generated by Django 6.0.1 on 2026-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edf_file', models.FileField(upload_to='eeg_records/%Y/%m/%d/')),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending AI Analysis'), ('processing', 'Processing Signal'), ('completed', 'Analysis Complete'), ('error', 'Processing Error')], default='pending', max_length=20)),
                ('seizure_probability', models.FloatField(blank=True, null=True)),
                ('dominant_frequency', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('channels_count', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('sampling_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EEG Analysis',
                'verbose_name_plural': 'EEG Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpectralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_power', models.FloatField()),
                ('beta_power', models.FloatField()),
                ('theta_power', models.FloatField()),
                ('delta_power', models.FloatField()),
                ('spectral_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
