# Generated by Django 6.0.1 on 2026-01-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeganalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='clinical.patient'),
        ),
    ]
