# Generated by Django 6.0.1 on 2026-01-28 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eeganalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spectralresult',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_data', to='analysis.eeganalysis'),
        ),
    ]
